# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI api-backend-architecture

on:
  push:
    branches: [ "main" ]

jobs:
  checkout-code:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

  install-dependencies:
    runs-on: self-hosted
    needs: checkout-code
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

  set-up-environment:
    runs-on: self-hosted
    needs: install-dependencies
    steps:
    - name: Set up environment variables
      run: echo "$ENV_FILE_CONTENT" > .env
      env:
        ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}

  run-tests:
    runs-on: self-hosted
    needs: [install-dependencies, set-up-environment]
    steps:
    - name: Run tests
      run: npm test

  start-application:
    runs-on: self-hosted
    needs: [install-dependencies, set-up-environment, run-tests]
    steps:
    - name: Start alive forever application
      run: /home/ubuntu/.nvm/versions/node/v16.20.1/bin/pm2 restart api-backend-architecture